from enum import Enum
from typing import Protocol

import torch

class CUMemHandleKind(Enum):
    Local = ...
    FileDescriptor = ...
    Fabric = ...

class CUMemMapping:
    @property
    def size(self) -> int: ...
    def data_ptr(self) -> int: ...
    def to_tensor(self, shape: tuple[int, ...], dtype: torch.dtype) -> torch.Tensor: ...
    def unmap(self) -> None: ...

class CUAllocHandle(Protocol):
    def map(self, device: torch.device | None = None) -> CUMemMapping: ...
    def map_to(self, mapping: CUMemMapping) -> None: ...

class CUMemAllocHandle(CUAllocHandle):
    def __init__(
        self,
        size: int,
        device: torch.device,
        handle_kind: CUMemHandleKind = CUMemHandleKind.Local,
    ) -> None: ...
    def export(self) -> CUMemExportHandle: ...

class CUMemImportHandle(CUAllocHandle): ...

class CUMemExportHandle:
    def bind(self) -> CUMemImportHandle: ...

class CUMulticastHandle(CUAllocHandle):
    def __init__(
        self,
        num_devices: int,
        size: int,
        handle_kind: CUMemHandleKind = CUMemHandleKind.Local,
    ) -> None: ...
    def export(self) -> CUMulticastExportHandle: ...
    def add_device(self, device_index: torch.device) -> None: ...
    def bind_mem(self, alloc_handle: CUMemAllocHandle) -> None: ...

class CUMulticastExportHandle:
    def bind(self) -> CUMulticastHandle: ...
